"""backet

Revision ID: 0d55054c9471
Revises: 637cf4f879c0
Create Date: 2025-02-23 14:01:47.093489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d55054c9471'
down_revision = '637cf4f879c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backet_user_id'), ['user_id'], unique=False)

    op.create_table('backet_products',
    sa.Column('backet_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backet_id'], ['backet.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('backet_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backet_products')
    with op.batch_alter_table('backet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backet_user_id'))

    op.drop_table('backet')
    # ### end Alembic commands ###
