"""banned статус

Revision ID: 24a3093166e5
Revises: 5c1d0f19fd68
Create Date: 2025-03-09 13:42:27.734641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a3093166e5'
down_revision = '5c1d0f19fd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
