"""order and backet

Revision ID: 3005a6a36ab4
Revises: e2786db9cb9b
Create Date: 2025-02-23 17:00:04.532979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3005a6a36ab4'
down_revision = 'e2786db9cb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('backet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('backet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
