"""update orders, link orders and users

Revision ID: 362680e2fb3f
Revises: 955673b75245
Create Date: 2025-02-16 20:48:04.872280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362680e2fb3f'
down_revision = '955673b75245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.drop_column('user_id')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('shipment_date')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
