"""reviews

Revision ID: 384759b47288
Revises: 867422e19658
Create Date: 2025-03-10 12:57:14.795315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384759b47288'
down_revision = '867422e19658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
