"""order_status

Revision ID: 42baec1b6100
Revises: dc6b8a1f79bb
Create Date: 2025-02-28 15:22:32.923195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42baec1b6100'
down_revision = 'dc6b8a1f79bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_status_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_status_id_fkey', 'user', ['status_id'], ['id'])

    # ### end Alembic commands ###
