"""order

Revision ID: 5c1d0f19fd68
Revises: a9adf39fd0ec
Create Date: 2025-03-08 16:08:14.216834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1d0f19fd68'
down_revision = 'a9adf39fd0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
