"""Product update

Revision ID: 63009f732cbf
Revises: 97cc98afa2a4
Create Date: 2025-02-16 14:33:27.831261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63009f732cbf'
down_revision = '97cc98afa2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
