"""test order_products

Revision ID: 637cf4f879c0
Revises: 7da3a838b25d
Create Date: 2025-02-16 22:41:09.831981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637cf4f879c0'
down_revision = '7da3a838b25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
