"""update orders

Revision ID: 887799b447ff
Revises: 362680e2fb3f
Create Date: 2025-02-16 20:53:23.043805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887799b447ff'
down_revision = '362680e2fb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
