"""order_status

Revision ID: 8c5ed74c229d
Revises: 42baec1b6100
Create Date: 2025-02-28 15:25:46.808929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5ed74c229d'
down_revision = '42baec1b6100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('order_status_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_status_id_fkey', 'order', ['status_id'], ['id'])
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
