"""many-to-many change

Revision ID: 92461329a38b
Revises: bf4d36ec81f8
Create Date: 2025-02-28 14:59:07.552971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92461329a38b'
down_revision = 'bf4d36ec81f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
