"""minor changes

Revision ID: bf4d36ec81f8
Revises: f5957d895834
Create Date: 2025-02-27 22:23:13.807768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4d36ec81f8'
down_revision = 'f5957d895834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('ix_role_name')
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))
        batch_op.create_index('ix_role_name', ['name'], unique=False)

    # ### end Alembic commands ###
