"""order_status

Revision ID: dc6b8a1f79bb
Revises: 45e34253e638
Create Date: 2025-02-28 15:07:28.682772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6b8a1f79bb'
down_revision = '45e34253e638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_name'), ['name'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_order_status_id'), ['status_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['status_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_status_id'))
        batch_op.drop_column('status_id')

    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_name'))

    op.drop_table('order_status')
    # ### end Alembic commands ###
