"""order and backet

Revision ID: e2786db9cb9b
Revises: f8d4bf4699b1
Create Date: 2025-02-23 16:44:31.838461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2786db9cb9b'
down_revision = 'f8d4bf4699b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'backet', ['backet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('backet_id')

    # ### end Alembic commands ###
