"""backet

Revision ID: f8d4bf4699b1
Revises: 28b1dc671d7d
Create Date: 2025-02-23 16:38:02.601086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d4bf4699b1'
down_revision = '28b1dc671d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backet_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('backet_products', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
